### ISSUE TITLE
AntlrKotlinTask is not compatible with Gradle 8.12

### ISSUE THREAD

**Issue by edwinRNDR** [Strumenta/antlr-kotlin#201]
When using AntlrKotlinTask in a Gradle 8.12 project I run into the following exception:

```
Caused by: java.lang.NoSuchMethodError: 'org.gradle.process.internal.AbstractExecHandleBuilder org.gradle.process.internal.JavaExecHandleBuilder.redirectErrorStream()'
	at com.strumenta.antlrkotlin.gradle.internal.AntlrWorkerManager.createWorkerProcess(AntlrWorkerManager.kt:40)
	at com.strumenta.antlrkotlin.gradle.internal.AntlrWorkerManager.runWorker(AntlrWorkerManager.kt:17)
	at com.strumenta.antlrkotlin.gradle.AntlrKotlinTask.execute(AntlrKotlinTask.kt:145)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:45)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.execute(IncrementalTaskAction.java:26)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:244)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:229)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:212)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:195)
	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:162)
	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
```

**Comment by ftomassetti** [comment]
Thank you for reporting this. We may specify which versions of gradle we support.
Would it be feasible for you to use gradle 8.8 for the time being?

**Comment by ftomassetti** [comment]
I am also running into this issue

**Comment by ftomassetti** [comment]
We may want to look into https://gradletest.ysb33r.org/gradletest/ to ensure the gradle plugin works with multiple versions of Gradle

**Comment by ftomassetti** [comment]
This is strange as the method causing the exception seems to be still there in the gradle codebase: https://github.com/gradle/gradle/blob/93844251a39b463e0d03b2b2853ae3acbca8bf50/subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java#L462

**Comment by ftomassetti** [comment]
And the ANTLR plugin (shipped with Gradle) keep using that call exactly as before:
https://github.com/gradle/gradle/blob/93844251a39b463e0d03b2b2853ae3acbca8bf50/platforms/software/antlr/src/main/java/org/gradle/api/plugins/antlr/internal/AntlrWorkerManager.java#L47

**Comment by fcavro** [comment]
> This is strange as the method causing the exception seems to be still there in the gradle codebase: https://github.com/gradle/gradle/blob/93844251a39b463e0d03b2b2853ae3acbca8bf50/subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java#L462

In Gradle 8.12, the `JavaExecHandleBuilder` class no longer subclasses `AbstractExecHandleBuilder`, but the bytecode of `AntlrWorkerManager` still expects `JavaExecHandleBuilder::redirectErrorStream`to return `AbstractExecHandleBuilder` (or at least as far as I understand it):
```
INVOKEVIRTUAL org/gradle/process/internal/JavaExecHandleBuilder.redirectErrorStream ()Lorg/gradle/process/internal/AbstractExecHandleBuilder;
```

**Comment by ftomassetti** [comment]
Oh, good point @fcavro . I guess we could call the method through reflection

**Comment by ftomassetti** [comment]
Release 1.0.2 is on its way, as this seems a problem worth to be solved asap

**Comment by lppedd** [comment]
Perfect, thanks @ftomassetti
