### ISSUE TITLE
OOM building project

### ISSUE THREAD

**Issue by raulraja** [Strumenta/antlr-kotlin#44]
hi!, 

I cloned and attempted to build the project in order to see if it is able to parse some .g4 files for which I want to generate models. When attempting to run seems like the native build is running OOM regardless of what JVM params I use. Any help is appreciated. thanks!
```
 !  ~/w/m/antlr-kotlin   …  ./gradlew clean build -DXmx6g -DXms16g                                                             4222ms  Fri May  1 23:42:23 2020
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Configure project :antlr-kotlin-runtime
Kotlin Multiplatform Projects are an experimental feature.

> Task :antlr-kotlin-gradle-plugin:compileJava
/Users/raulraja/workspace/misc/antlr-kotlin/antlr-kotlin-gradle-plugin/src/main/java/com/strumenta/antlrkotlin/gradleplugin/AntlrKotlinTask.java:25: warning: [deprecation] IncrementalTaskInputs in org.gradle.api.tasks.incremental has been deprecated
import org.gradle.api.tasks.incremental.IncrementalTaskInputs;
                                       ^
/Users/raulraja/workspace/misc/antlr-kotlin/antlr-kotlin-gradle-plugin/src/main/java/com/strumenta/antlrkotlin/gradleplugin/AntlrKotlinTask.java:196: warning: [deprecation] IncrementalTaskInputs in org.gradle.api.tasks.incremental has been deprecated
    public void execute(IncrementalTaskInputs inputs) {
                        ^
2 warnings
Expiring Daemon because JVM heap space is exhausted
Daemon will be stopped at the end of the build after running out of JVM memory
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted

> Task :antlr-kotlin-runtime:compileKotlinNative FAILED
e: Compilation failed: Java heap space

 * Source files: Misc.kt, ANTLRErrorListener.kt, ANTLRErrorStrategy.kt, ANTLRFileStream.kt, ANTLRInputStream.kt, AbstractCharStreams.kt, BailErrorStrategy.kt, BaseErrorListener.kt, BufferedTokenStream.kt, CharStream.kt, CharStreams.kt, CommonToken.kt, CommonTokenFactory.kt, CommonTokenStream.kt, ConsoleErrorListener.kt, DefaultErrorStrategy.kt, DiagnosticErrorListener.kt, FailedPredicateException.kt, InputMismatchException.kt, IntStream.kt, InterpreterRuleContext.kt, Lexer.kt, LexerInterpreter.kt, LexerNoViableAltException.kt, ListTokenSource.kt, NoViableAltException.kt, Parser.kt, ParserInterpreter.kt, ParserRuleContext.kt, ProxyErrorListener.kt, RecognitionException.kt, Recognizer.kt, RuleContext.kt, RuleContextWithAltNum.kt, RuntimeMetaData.kt, StringCharStream.kt, Token.kt, TokenFactory.kt, TokenSource.kt, TokenStream.kt, TokenStreamRewriter.kt, UnbufferedCharStream.kt, UnbufferedTokenStream.kt, Vocabulary.kt, VocabularyImpl.kt, WritableToken.kt, Node.kt, position.kt, ATN.kt, ATNConfig.kt, ATNConfigSet.kt, ATNDeserializationOptions.kt, ATNDeserializer.kt, ATNSerializer.kt, ATNSimulator.kt, ATNState.kt, ATNType.kt, AbstractPredicateTransition.kt, ActionTransition.kt, AmbiguityInfo.kt, ArrayPredictionContext.kt, AtomTransition.kt, BasicBlockStartState.kt, BasicState.kt, BlockEndState.kt, BlockStartState.kt, CodePointTransitions.kt, ContextSensitivityInfo.kt, DecisionEventInfo.kt, DecisionInfo.kt, DecisionState.kt, EmptyPredictionContext.kt, EpsilonTransition.kt, ErrorInfo.kt, LL1Analyzer.kt, LexerATNConfig.kt, LexerATNSimulator.kt, LexerAction.kt, LexerActionExecutor.kt, LexerActionType.kt, LexerChannelAction.kt, LexerCustomAction.kt, LexerIndexedCustomAction.kt, LexerModeAction.kt, LexerMoreAction.kt, LexerPopModeAction.kt, LexerPushModeAction.kt, LexerSkipAction.kt, LexerTypeAction.kt, LookaheadEventInfo.kt, LoopEndState.kt, NotSetTransition.kt, OrderedATNConfigSet.kt, ParseInfo.kt, ParserATNSimulator.kt, PlusBlockStartState.kt, PlusLoopbackState.kt, PrecedencePredicateTransition.kt, PredicateEvalInfo.kt, PredicateTransition.kt, PredictionContext.kt, PredictionContextCache.kt, PredictionMode.kt, ProfilingATNSimulator.kt, RangeTransition.kt, RuleStartState.kt, RuleStopState.kt, RuleTransition.kt, SemanticContext.kt, SetTransition.kt, SingletonPredictionContext.kt, StarBlockStartState.kt, StarLoopEntryState.kt, StarLoopbackState.kt, TokensStartState.kt, Transition.kt, WildcardTransition.kt, DFA.kt, DFASerializer.kt, DFAState.kt, LexerDFASerializer.kt, AbstractEqualityComparator.kt, Array2DHashSet.kt, DoubleKeyMap.kt, EqualityComparator.kt, FlexibleHashMap.kt, IntSet.kt, IntegerList.kt, IntegerStack.kt, InterpreterDataReader.kt, Interval.kt, IntervalSet.kt, LogManager.kt, MultiMap.kt, MurmurHash.kt, NotNull.kt, ObjectEqualityComparator.kt, OrderedHashSet.kt, ParseCancellationException.kt, Predicate.kt, Utils.kt, AbstractParseTreeVisitor.kt, ErrorNode.kt, ErrorNodeImpl.kt, IterativeParseTreeWalker.kt, ParseTree.kt, ParseTreeListener.kt, ParseTreeProperty.kt, ParseTreeVisitor.kt, ParseTreeWalker.kt, RuleNode.kt, SyntaxTree.kt, TerminalNode.kt, TerminalNodeImpl.kt, Tree.kt, Trees.kt, Chunk.kt, ParseTreeMatch.kt, ParseTreePattern.kt, ParseTreePatternMatcher.kt, RuleTagToken.kt, TagChunk.kt, TextChunk.kt, TokenTagToken.kt, XPath.kt, XPathElement.kt, XPathLexer.kt, XPathLexerErrorListener.kt, XPathRuleAnywhereElement.kt, XPathRuleElement.kt, XPathTokenAnywhereElement.kt, XPathTokenElement.kt, XPathWildcardAnywhereElement.kt, XPathWildcardElement.kt, BitSet.kt, Collections.kt, IdentityHashMap.kt, UUID.kt, WeakHashMap.kt, arrays.kt, chars.kt, logging.kt, sync.kt, type.kt, CharStreams.kt
 * Compiler version info: Konan: 1.3.70 / Kotlin: 1.3.70
 * Output kind: LIBRARY

e: java.lang.OutOfMemoryError: Java heap space
        at java.nio.file.Files.read(Files.java:3099)
        at java.nio.file.Files.readAllBytes(Files.java:3158)
        at org.jetbrains.kotlin.konan.file.File.readBytes(File.kt:124)
        at org.jetbrains.kotlin.library.impl.MetadataLibraryImpl$packageMetadata$1.invoke(KotlinLibraryImpl.kt:54)
        at org.jetbrains.kotlin.library.impl.MetadataLibraryImpl$packageMetadata$1.invoke(KotlinLibraryImpl.kt:42)
        at org.jetbrains.kotlin.library.impl.BaseLibraryAccess.inPlace(KotlinLibraryLayoutImpl.kt:70)
        at org.jetbrains.kotlin.library.impl.MetadataLibraryImpl.packageMetadata(KotlinLibraryImpl.kt:53)
        at org.jetbrains.kotlin.konan.library.impl.KonanLibraryImpl.packageMetadata(KonanLibraryImpl.kt)
        at org.jetbrains.kotlin.library.metadata.PackageAccessHandler$DefaultImpls.loadPackageFragment(KlibMetadataDeserializationUtils.kt:25)
        at org.jetbrains.kotlin.library.resolver.KotlinResolvedLibrary$DefaultImpls.loadPackageFragment(KotlinResolvedLibrary.kt)
        at org.jetbrains.kotlin.library.resolver.impl.KotlinResolvedLibraryImpl.loadPackageFragment(KotlinResolvedLibraryImpl.kt:9)
        at org.jetbrains.kotlin.library.metadata.KlibMetadataDeserializedPackageFragment$protoForNames$2.invoke(KlibMetadataPackageFragment.kt:34)
        at org.jetbrains.kotlin.library.metadata.KlibMetadataDeserializedPackageFragment$protoForNames$2.invoke(KlibMetadataPackageFragment.kt:22)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.library.metadata.KlibMetadataDeserializedPackageFragment.getProtoForNames(KlibMetadataPackageFragment.kt)
        at org.jetbrains.kotlin.library.metadata.KlibMetadataPackageFragment.loadClassNames(KlibMetadataPackageFragment.kt:106)
        at org.jetbrains.kotlin.library.metadata.KlibMetadataPackageFragment.access$loadClassNames(KlibMetadataPackageFragment.kt:52)
        at org.jetbrains.kotlin.library.metadata.KlibMetadataPackageFragment$classifierNames$2.invoke(KlibMetadataPackageFragment.kt:97)
        at org.jetbrains.kotlin.library.metadata.KlibMetadataPackageFragment$classifierNames$2.invoke(KlibMetadataPackageFragment.kt:52)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.library.metadata.KlibMetadataPackageFragment.getClassifierNames(KlibMetadataPackageFragment.kt)
        at org.jetbrains.kotlin.library.metadata.KlibMetadataPackageFragment.hasTopLevelClassifier(KlibMetadataPackageFragment.kt:102)
        at org.jetbrains.kotlin.backend.common.serialization.metadata.impl.ClassifierAliasingPackageFragmentDescriptor$memberScope$1.getContributedClassifier(KlibMetadataDeserializedPackageFragmentsFactoryImpl.kt:129)
        at org.jetbrains.kotlin.resolve.scopes.ChainedMemberScope.getContributedClassifier(ChainedMemberScope.kt:33)
        at org.jetbrains.kotlin.resolve.scopes.AbstractScopeAdapter.getContributedClassifier(AbstractScopeAdapter.kt:44)
        at org.jetbrains.kotlin.descriptors.FindClassInModuleKt.findClassifierAcrossModuleDependencies(findClassInModule.kt:25)
        at org.jetbrains.kotlin.descriptors.FindClassInModuleKt.findClassAcrossModuleDependencies(findClassInModule.kt:40)
        at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer.computeClassDescriptor(TypeDeserializer.kt:221)
        at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer.access$computeClassDescriptor(TypeDeserializer.kt:23)
        at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer$classDescriptors$1.invoke(TypeDeserializer.kt:32)
        at org.jetbrains.kotlin.serialization.deserialization.TypeDeserializer$classDescriptors$1.invoke(TypeDeserializer.kt:23)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:512)

Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':antlr-kotlin-runtime:compileKotlinNative'.
> Compilation finished with errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 46s
12 actionable tasks: 10 executed, 2 up-to-date
Expiring Daemon because JVM heap space is exhausted
```

**Comment by ftomassetti** [comment]
This is more of a question and I guess it is a little late to answer it. Closing it, as suggested by @lppedd
